import type { Metadata } from "next";
import "@/app/globals.css";
import Cabecalho from "@/components/Cabecalho/Cabecalho";


export const metadata: Metadata = {
  title: "Portfolio de Alunos",
  description: "Generated by create next app",
};

export const viewport = {
  width:"device-width",
  initial_scale:1.0,
  colorScheme:"dark"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Cabecalho />
        {children}
      </body>
    </html>
  );
}
